version: "3"
services:
  app:
    build: .
    container_name: homesite-app
    command:
      [sh, -c, "gunicorn --bind 0.0.0.0:8000 homesite.wsgi:application"]
    ports:
      - 8000:8000
    volumes:
      - ./static:/app/static
      - ./data.db:/app/data.db
      - ./logs:/app/logs
    restart: unless-stopped

  bot:
    build: .
    container_name: homesite-bot
    command: [sh, -c, "python discordbot/bot.py"]
    volumes:
      - ./data.db:/app/data.db
      - ./discordbot:/app/discordbot
      - ./logs:/app/logs
    restart: always
